[llvm] Provide separate veclib mappig of PGMATH functions for AArch64 (release 14x)
flang-compiler/classic-flang-llvm-project pull request #130
Opened 2022-08-01 21:25 UTC by pawosm-arm

This patch fixes link-time issues experienced while compiling some
more obscure Fortran workloads. For those programs, calls to the
libpgmath functions not defined for AArch64 were generated, e.g.
`__pg_log_4` or `__fd_log_4`. This patch eliminates such possibility.

2022-08-24 15:02 UTC, bryanpkc commented
We have done something similar downstream, but for `release_14x` branch, we moved these libpgmath function mappings into `llvm/include/llvm/Analysis/VecFuncs.def`, as is done for all other libraries handled by TargetLibraryInfo.cpp.

2022-09-07 11:05 UTC, bryanpkc requested changes
Please refactor this patch to use `llvm/Analysis/VecFuncs.def` as described in my previous comment.

2022-09-12 15:46 UTC, pawosm-arm commented
The macOS bug is unrelated to this commit.

2022-09-12 17:31 UTC, pawosm-arm commented
> Please refactor this patch to use `llvm/Analysis/VecFuncs.def` as described in my previous comment.

@bryanpkc is it ok now?

2022-09-12 17:54 UTC, bryanpkc approved these changes
Yep, LGTM. Thanks for refactoring!

2022-09-13 06:57 UTC, merged