Delete pgmath veclib definitions for sincos for release14
flang-compiler/classic-flang-llvm-project pull request #136
Opened 2022-10-20 13:09 UTC by gbaraldi

Rebase of #132 on release_14x. I also deleted the aarch64 functions, but I haven't tested if they caused problems like the x86 ones. A rough guess would be that they also do, because pgmath does that weird vector thing.

2022-10-21 08:32 UTC, pawosm-arm requested changes
There are two issues here, a small one and a big one.
A small one: the commit message should reflect what the commit actually does (apart from being merely rebase)
A big one: the 'I haven't tested' part of PR message is a red flag. This commit lacks a test case: something that would fail without this commit and passes with it. I.e. it would make it so much easier for me to e.g. verify that the AArch64 change is actually needed.

2022-10-21 13:24 UTC, gbaraldi commented
From #11 it seems that
```fortran
program foo
      real(kind=8) :: val, res1, res2
      read *, val
      res1 = sin(val)
      res2 = cos(val)
      print *, res1, res2
end program foo
```
This fails to build with O1 before this PR, but works with it. Where should this test go?

2022-10-21 16:26 UTC, pawosm-arm commented
I've forgotten we're not in the (classic) flang repo. This test would have to go to f90_correct directory in the other repo, which would create artificial detachment we'd like to avoid.

I've tried your reproducer on AArch64, and it didn't fail. In the end, my commit that you're modifying here appeared after my failed attempt to build SPEC2k17. The things that were missing for AArch64 were already removed.

I'll try to build libpgmath for AArch64 a different way, I'll let you know if it still fails to fail.

I'm testing debug build with assertsions turned on.

2022-10-21 16:42 UTC, pawosm-arm commented
No matter how I try, it isn't failing on AArch64.

Could you prepare a PR on classic flag repo with your reproducer in the f90_correct directory? In theory, it should fail on x86_64 and pass on AArch64. Depending on the outcome, we shall approve this PR or not.

2022-11-19 22:21 UTC, pawosm-arm commented
The reproducer cannot still prove that the problem occurs on AArch64, even after we have added assertions-enabled builds in our CI. Therefore I would like to ask the contributor to remove the AArch64 part from the commit.

2022-11-21 16:01 UTC, bryanpkc commented
I have just restarted the CIs on flang-compiler/flang#1310 with assertions-enabled builds. The last time they were run (27 days ago), assertions had not been enabled yet.

2022-11-21 17:00 UTC, pawosm-arm commented
> I have just restarted the CIs on [flang-compiler/flang#1310](https://github.com/flang-compiler/flang/pull/1310) with assertions-enabled builds. The last time they were run (27 days ago), assertions had not been enabled yet.

Yeah, but the failure on x86 is what we expected, while AArch64 failure is about opaque pointers, which is rather odd... Did we enable opaque pointers for release_14x branch?

2022-11-21 17:22 UTC, bryanpkc commented
@pawosm-arm 

>　Did we enable opaque pointers for release_14x branch?

No, opaque pointers are not enabled for the `release_14x` branch. However, https://github.com/flang-compiler/flang/pull/1310 needs to be rebased, and the PR itself edited, to target `legacy` instead of `master`.

2022-11-29 22:24 UTC, pawosm-arm approved these changes
Merge instruction: please squash the commits while merging.

2022-11-29 22:29 UTC, bryanpkc approved these changes

2022-11-30 16:13 UTC, shivaramaarao approved these changes

2022-11-30 19:33 UTC, merged