Add platform independent build script for LLVM (release_15x)
flang-compiler/classic-flang-llvm-project pull request #145
Opened 2022-11-30 17:09 UTC by tdusnoki

2022-12-17 00:20 UTC, bryanpkc requested changes
My comments for #134 apply here as well.

2023-01-11 21:38 UTC, bryanpkc approved these changes
LGTM

2023-01-12 15:23 UTC, kaadam commented on scripts/build_llvm_project.py
> +    additional_options.append('-DLLVM_ENABLE_PROJECTS='+'; '.join(['%s']*len(arguments.llvm_enable_projects)) % tuple(arguments.llvm_enable_projects))
Seems this expression is a bit complex, I think we can simplify it a bit.
What about this?
'-DLLVM_ENABLE_PROJECTS={}'.format(";".join([str(item) for item in arguments.llvm_enable_projects]))
Maybe you can leave the generator expression so just use ....format(";".join(arguments.llvm_enable_projects)))
Of course you should change the default value in the argument definition -> default=['clang', 'openmp']

2023-01-13 11:23 UTC, kaadam approved these changes
LGTM

2023-01-14 12:46 UTC, merged