Fix for issue 1440 (make Mbackslash as the default option in flang)
flang-compiler/classic-flang-llvm-project pull request #180
Opened 2024-04-21 05:23 UTC by shivaramaarao

Through this commit Mbackslash will be the default option. By default, escape characters are treated as regular characters unless Mnobackslash is specified.

2024-05-15 07:52 UTC, bryanpkc commented on clang/lib/Driver/ToolChains/ClassicFlang.cpp
> +    BackSlashOptionPresent = true;
Shouldn't these two `for` loops be combined, to handle all four options at once? Currently when the `-fbackslash -fno-backslash` command-line options are specified in that order, the driver gives this surprising behaviour (overriding `-x 124 0x40` with `-y 124 0x40`):
```
".../bin/flang1" foo.f90 -opt 0 -terse 1 -inform warn -nohpf -nostatic -cmdline "'+flang -fbackslash -fno-backslash foo.f90 -v'" -inform warn -x 124 0x40 -y 124 0x40 -y 129 2 -ieee 1 ...
```

2024-05-15 08:00 UTC, bryanpkc requested changes
The option processing is buggy and should be fixed. The test case `clang/test/Driver/flang/classic-flang.f95` should be updated to cover the relevant options.

2024-06-26 14:00 UTC, bryanpkc commented on clang/lib/Driver/ToolChains/ClassicFlang.cpp
> +                                  options::OPT_Mnobackslash)) {
Why does this code claim the options in two separate loops? Can't it claim all of them in a single loop?

2024-06-26 14:01 UTC, bryanpkc commented on clang/lib/Driver/ToolChains/ClassicFlang.cpp
> +      CommonCmdArgs.push_back("0x40");
Incorrect indentation. Please use `clang-format` on the diff.

2024-06-26 14:02 UTC, bryanpkc commented on clang/lib/Driver/ToolChains/ClassicFlang.cpp
> +       A->claim();
`A` has already been claimed by this point.

2024-07-02 15:35 UTC, bryanpkc approved these changes
LGTM.

2024-07-02 16:08 UTC, pawosm-arm approved these changes

2024-07-03 06:21 UTC, merged