gcc11-introduce
flang-compiler/classic-flang-llvm-project pull request #80
Opened 2021-12-15 13:47 UTC by pwisniewskimobica

Switch to gcc11 and g++11

2021-12-15 15:19 UTC, pwisniewskimobica commented
We want to introduce compilation with gcc-11 in Flang CI.
This PR lets us build the gcc-11 artifacts for later use in Flang repository CI which is done in
flang-compiler/flang#1190

2022-01-26 15:52 UTC, bryanpkc approved these changes
LGTM

2022-01-27 13:48 UTC, bryanpkc commented
I would suggest rewording the commit to something like:
```
Use GCC 11 in CI builds
```

2022-01-27 13:54 UTC, pawosm-arm requested changes

2022-01-27 13:54 UTC, pawosm-arm commented on .github/workflows/pre-compile_llvm.yml
> +    branches: [ release_100, release_11x, release_12x, release_13x]
As @bryanpkc said before, please keep spaces where they were...

2022-01-27 14:00 UTC, pwisniewskimobica commented on .github/workflows/pre-compile_llvm.yml
> +    branches: [ release_100, release_11x, release_12x, release_13x]
-->fixed

2022-02-15 10:34 UTC, RichBarton-Arm approved these changes
Happy to approve from Arm.

@shivaramaarao - happy to put this on 12 also?

2022-02-25 10:06 UTC, RichBarton-Arm commented
As per the policy, only one approval is needed on CI changes, so I am just going to merge this.

2022-02-25 10:06 UTC, merged

2022-03-05 17:26 UTC, bryanpkc commented
@RichBarton-Arm  For future reference, please avoid merge commits. They make it hard to see what happened in one-line git logs.